language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
before_install:
install:
- pip install requests
- pip install bs4
- pip install ujson
notifications:
after_success:
script: python -m unittest -v unit_tests.TestPymoe
